---
- name: Copy SSH Key | [joeythelantern]
  become: yes
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', '/home/joeythelantern/.ssh/id_rsa.pub') }}"
  with_items:
    - "{{ ssh.users }}"
...